### PR TITLE
some minor housekeeping

### PR DESCRIPTION
**Pull request by kylemac**
i'm using my new found collaborator status to do a few housekeeping things that bug me and [probably] only me.

### CODE REVIEW

**Comment by hhsnopek** [comment]
I don't think you've defined `console`
:dog2:

**Comment by jenius** [comment]
Honestly, not sold on "hound" at all. I always am just deleting it's messages -_____-

**Comment by hhsnopek** [comment]
@jenius you need to add a `.jshint` file so that it knows what to be parsing. The default options are [here](https://raw.githubusercontent.com/thoughtbot/hound/master/config/style_guides/javascript.json). You need to add `node: true` for it to stop yelling at you for `console.log` errors :grinning:

**Comment by jenius** [comment]
Alternately I could NOT USE IT AT ALL!

**Pull request merged**
