### PR TITLE
Add sprout 0.3.x compatibility

### PR DESCRIPTION
**Pull request by nporteschaikin**
Still ned to discuss generator support.

cc/ @jenius @kylemac

### CODE REVIEW

**Comment by jenius** [comment]
Ok so failing tests and a couple hound comments here, any chance you could patch those up then I'll take another look?

Also we need to talk about how exactly this will break things. Have we done any tests on machines that have the previous version installed? Do all templates break? What is your plan for smoothly upgrading here without messing up people's stuff?

**Comment by nporteschaikin** [comment]
@jenius :tennis: :point_up:

**Comment by jenius** [comment]
Sorry for the delay, will take a look at this in the next couple days for sure :+1:

**Comment by jenius** [comment]
Closing bc of #644

**Pull request closed without merging**
