### PR TITLE
update all dependencies

### PR DESCRIPTION
**Pull request by jenius**
Some were in dire need of an update. Also get tests running on the latest version of node. Whoo!

### CODE REVIEW

**Comment by jenius** [comment]
Ok so all the tests here are passing. This is good. The only thing that needs to be ironed out is whether the weird image clipping issue is occurring still.

**Comment by dbox** [comment]
You mean #655? I posted a test repo in there you can check against.

**Comment by jenius** [comment]
Can confirm that the image issue is present. This really needs to be worked out in order for roots to move forward at all. I am going to start hacking on this with any free time I have.

**Comment by dbox** [comment]
And there was much rejoicing.

Thanks!! You're the best.

**Comment by jenius** [comment]
Unfortunately I have very little free time, but I'll do my best!

**Comment by jenius** [comment]
Just did a small test and this should fix #659 :tada:

**Comment by dbox** [comment]
:open_mouth: :open_mouth: :tada:

**Comment by dbox** [comment]
were you able to isolate something that was throwing `roots segmentation fault` ?

**Comment by jenius** [comment]
yeah i had one project that would consistently throw it, after this upgrade it no longer is

**Comment by jenius** [comment]
Ok, can confirm that the broken image issue is coming from the livereload system, specifically from infector. If this is disabled, images work correctly. Will have a fix ready for this soon, then we can push out the release!

**Comment by jenius** [comment]
Browsersync merge takes care of this :tada:

**Pull request closed without merging**
