### PR TITLE
Roots v3

### PR DESCRIPTION
**Pull request by jenius**
Opening this up just to keep track of the to-do list and such.

- [x] basic compile
- [x] live reload
- [x] compiler options
- [x] before/after hooks
- [x] multipass compiles
- [x] precompiled templates (extension)
- [x] dynamic content (extension)
- [x] environments
- [x] debug mode
- [x] source maps
- [x] deployment (ship)
- [x] 95%+ test coverage
- [x] complete documentation for all features and usage

### CODE REVIEW

**Comment by jenius** [comment]
Ok guys it's time for merge. Any final objections? If not this will be merged in the next half hour and we will be live!

**Comment by joshrowley** [comment]
:+1: 

:tada: :clap: :confetti_ball: :clap: :tada: :clap:  :confetti_ball: 

Well done @jenius.

**Comment by ccsouthard** [comment]
​Site looks great! Looking forward to the videos. Nice work @jenius​

**Comment by jenius** [comment]
@ccsouthard 4 videos already up, check it out! http://roots.netlify.com

**Pull request merged**
