### PR TITLE
Environment merge

### PR DESCRIPTION
**Pull request by joshrowley**
This PR adds functionality to how environments are loaded into roots. If you have an environment file, such as `app.production.coffee`, roots will now merge the locals and extensions from the environment file  into the default `app.coffee` locals and extensions.

This is useful for keeping locals and extension configurations DRY across environments. This way you only need to add locals into the environment specifc config that need to override values in the main `app.coffee`. I found this useful to prevent having to duplicate a lot of helper functions and values in my locals across environments.

When it comes to extensions, since they're already called functions we can't replace the options that were already passed in. So instead, if you have an extension in your environment specific config that matches in class name with one from your `app.coffee`, the environment specific one completely replaces it.

### CODE REVIEW

**Comment by joshrowley** [comment]
Also, we can do this for other config options in `app.coffee` (like `server` and the boolean options), but I wanted to start with the ones I would personally find the most useful

**Comment by jenius** [comment]
Sorry for the delay, going to take a look at this tomorrow :grinning:

**Comment by jenius** [comment]
This is looking good! Just a couple small things, and also is there any reason tests aren't passing on travis?

**Comment by joshrowley** [comment]
@jenius Yeah, I think I broke handling `app.coffee` files that don't export node style. Will have fix soon.

**Comment by joshrowley** [comment]
@jenius nevermind, all that was mine, just needed to set a default empty array for extensions if the conf file didn't have that key.

**Comment by joshrowley** [comment]
yay, tests passing :+1:

**Comment by joshrowley** [comment]
@jenius One issue that @nporteschaikin brought up (in Slack) is that the extension replacement logic won't work if the extension doesn't have a `name` property (i.e. you use an anonymous function)

**Comment by jenius** [comment]
Hmm ok, perhaps we should enforce a name then and add a test for this before merging, just to be thorough? Does this seem reasonable? I feel like there are many reasons why a name should be required anyway.

**Comment by jenius** [comment]
Ping!

**Comment by joshrowley** [comment]
Yup, will add that name check!

**Comment by jenius** [comment]
Ok maybe we should just merge this up?

**Comment by eholzwarth** [comment]
@jenius @joshrowley What is the status on this PR? I would like to use it :)

**Comment by eholzwarth** [comment]
Any reason this can't be merged now? It is a real bummer to maintain parallel versions of app.coffee

**Comment by ryanjbonnell** [comment]
+1

**Comment by jenius** [comment]
Closing as this is way to far out of date and doesn't seem like it will be brought up to date.

For now to work around, just `require('./app')` from your main config, customize and export it. The next version of roots will have automatic merge like this.

**Pull request closed without merging**
