### PR TITLE
Special layout files now work (https://github.com/jenius/roots/pull/379)

### PR DESCRIPTION
**Pull request by grin**
This implements a fix from https://github.com/jenius/roots/pull/379 on the v2 branch.

### CODE REVIEW

**Comment by samccone** [comment]
:+1: working just dandy on our project @jenius but wanted to just get your eyes on it, and maybe get a nice lil 2.15 release out :)

**Comment by jenius** [comment]
Looks good to me. I'll push a release with this shortly. Sorry this was unresolved for so long!

**Comment by samccone** [comment]
:boom: thanks @jenius

**Comment by jenius** [comment]
This was also shipped as `roots@2.1.5`

**Pull request merged**
